steps:
- name: 'node:10.16.3'
    entrypoint: 'yarn'
    args: ["yarn", "install --frozen-lockfile"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'
